Tree handler
Ichenn92/tree-visualizer pull request #3
Opened 2020-10-08 21:13 UTC by Ichenn92

2020-10-13 18:47 UTC, divad1196 requested changes

2020-10-13 18:47 UTC, divad1196 commented on app/controllers/homepage_controller.rb
> +    tree.rebalance!
pourquoi rebalancer l'arbre?

2020-10-13 18:47 UTC, divad1196 commented on app/javascript/components/Editor.jsx
> +    this.state.code += "\ntree.run";
il se passe quoi avec tree.run dans ton code?

2020-10-13 18:47 UTC, divad1196 commented on app/javascript/components/Editor.jsx
> +	{this.state.runCode && this.generateTree(this.state.code)}
NameError (undefined local variable or method `continue' for #<HomepageController:0x00007f8164714548>):
  
(eval):12:in `run'
app/controllers/homepage_controller.rb:13:in `eval'
app/controllers/homepage_controller.rb:13:in `run'


aussi, ta méthode ne retourne rien, donc l'afficher ici n'est pas utile.
Quand tu run le code, fait directement la query

2020-10-13 19:04 UTC, Ichenn92 commented on app/controllers/homepage_controller.rb
> +    tree.rebalance!
c'était un test de la librairie

2020-10-13 19:08 UTC, Ichenn92 commented on app/javascript/components/Editor.jsx
> +    this.state.code += "\ntree.run";
il renvoie la liste de l'objet Tree. based_value + les méthodes
et ensuite il clean l'objet

2020-10-13 19:13 UTC, Ichenn92 commented on app/javascript/components/Editor.jsx
> +	{this.state.runCode && this.generateTree(this.state.code)}
la méthode ne retourne actuellement rien. mais elle transmet bien les informations depuis le serveur. ça jai pas compris pourquoi ca arrivait pas au front

2020-10-16 10:39 UTC, divad1196 reviewed
Quelques commentaires en plus

2020-10-16 10:39 UTC, divad1196 commented on app/controllers/homepage_controller.rb
> +    render json: eval(code[:code])
Tu renvoies depuis le frontend un dict avec ta string.
Est-ce qu'il y autre chose dans le dict? Sinon tu peux simplement retourner depuis le frontend que la string. Et la réponse reste un dict en json.

2020-10-16 10:39 UTC, divad1196 commented on app/javascript/components/Editor.jsx
> +    this.updateCode = this.updateCode.bind(this);
Bind aussi generateTree
J ai pas encore pu tester mais je l avais bind quand je pense que ça marchait sans soucis

2020-10-16 10:39 UTC, divad1196 commented on app/javascript/components/Editor.jsx
> +    this.state.values = [];
Pourquoi tu fais ces actions?
Surtout sans passer par setState?

2020-10-16 10:39 UTC, divad1196 commented on app/views/homepage/index.html.erb
> +<h2>Codemirror</h2>
Top de pas avoir mis cette balise dans le composant.
Tu sépares le label du composant

2020-10-16 10:39 UTC, divad1196 commented on lib/trees_api.rb
> +  def initialize array
Tout est top.
Faudra voir si on veut pouvoir traiter plusieurs arbres

2020-10-16 10:51 UTC, Ichenn92 commented on app/controllers/homepage_controller.rb
> +    render json: eval(code[:code])
C'est un dictionnaire de paramètres
Ça permet de sécurisé les paramètres entrants et d'accepter que ce dont tu as besoin

2020-10-16 19:49 UTC, Ichenn92 commented on app/javascript/components/Editor.jsx
> +    this.state.values = [];
aucune raison, j'avais mis ça quand je voulais tester si ca pouvait trigger le re-render.
oubliais de les supprimer. bien vu!

2020-10-16 19:54 UTC, Ichenn92 commented on app/javascript/components/Editor.jsx
> +    this.updateCode = this.updateCode.bind(this);
j'ai essayé avec le bind mais ca ne fonctionne pas non plus

2020-10-18 09:11 UTC, divad1196 commented on app/controllers/homepage_controller.rb
> +    render json: eval(code[:code])
Pour le coup non.
Tu parles de la sanitarisation je pense.
Elle est là pour vérifier que quand tu reçois un GROUPE de donnée, que tu la reçoives avec que ce dont tu as besoin et dans le type dont tu as besoin.

Tu ne fais pas de check de type ici, et quand tu reçois une seule donnée tu peux directement appliquer tes check sur elle si tu as.

Ici le seul check que tu fais c'est vérifier qu'il y a une donnée du nom "code", mais si c'est la seule donnée que tu as ça sert à rien. Ca t assure pas que la donnée "code" est celle que tu attends.

2020-10-18 09:18 UTC, divad1196 reviewed
D autres remarques

2020-10-18 09:18 UTC, divad1196 commented on app/controllers/homepage_controller.rb
> +    params.require(:homepage).permit(:code)
Typiquement, en attend qu'une string et pas un dict avec une seule string, tu n'aurais pas besoin de ce check

Juste de verifier le type

2020-10-18 09:18 UTC, divad1196 commented on app/javascript/components/Editor.jsx
> +  constructor() {
Je me demande si tu devrais pas prendre props et le passer à super meme si tu l utilises pas

Je dois revoir la doc je pense sur ce point
Je validerai la PR en l etat si y a que ce point

2020-10-18 09:18 UTC, divad1196 commented on app/javascript/components/Editor.jsx
> +          nbr_actions: [data.actions.length]
Pourquoi garder une liste avec 1 element dedans?

2020-10-18 09:30 UTC, Ichenn92 commented on app/javascript/components/Editor.jsx
> +          nbr_actions: [data.actions.length]
erreur de ma part.
c'était quand je croyais que c'était lié au props du composant appelé.
je le met en integer

2020-10-18 09:33 UTC, Ichenn92 commented on app/controllers/homepage_controller.rb
> +    render json: eval(code[:code])
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/58181470/96363610-c0c4e480-1135-11eb-8473-3f242a670e75.png">

2020-10-18 09:34 UTC, Ichenn92 commented on app/controllers/homepage_controller.rb
> +    render json: eval(code[:code])
non c'est important. car si tu fais pas ce check il peut importer d'autres données.

c'est dans la doc rails

2020-10-18 09:34 UTC, Ichenn92 commented on app/controllers/homepage_controller.rb
> +    params.require(:homepage).permit(:code)
quand je reçois les paramètres, c'est un dictionnaire. voir mon commentaire ci-dessus

2020-10-18 13:09 UTC, divad1196 commented on app/javascript/components/Editor.jsx
> +          nbr_actions: data.actions
tu remets une liste ici

Aussi t'es pas garantie que le nombre d'actions ait changé (tu peux avoir 3 add, ou 3 delete, ça change rien)

fait un compteur de run à la place

runCount: this.state.runCount + 1

en tout cas, qqch d'indépendant du résultat reçu

2020-10-18 14:46 UTC, merged